---
title: "NES-LTER Particulate organic carbon and nitrogen from MVCO data package for EDI"
author: "Joe Futrelle"
date: "2023-03-21"
output: html_notebook
---

Libraries used

```{r}
# two of the required packages are installed from GitHub
# library(remotes)
# remotes::install_github("EDIorg/EMLassemblyline")
# remotes::install_github("WHOIGit/ediutilities")

library(EMLassemblyline)
library(ediutilities)
library(here)
library(lubridate)
library(readxl)
library(dplyr)
```

Read data table

```{r}
poc_mvco <- read.csv(here('MVCO_poc_4EDI_20250707.csv'))
```

Add Tioga cruise number

```{r}

df <- read_excel('List of MVCO cruises for NES-LTER project 20250523.xlsx', sheet = "catalog", skip = 6)
Tioga_ID <- df %>% select(1, 3, 4, 5)

poc_mvco <- left_join(poc_mvco, Tioga_ID, by = "event_number")

poc_mvco <- poc_mvco %>%
  select(-date)  %>%

  relocate(ship, .before = date_time_utc) %>%
  relocate(cruise, .before = date_time_utc)

poc_mvco <- poc_mvco %>%
  rename(cruise_ID = cruise)

poc_mvco[] <- lapply(poc_mvco, function(x) {
  if (is.character(x)) x[x == "NA"] <- NA
  return(x)
})

```

```{r}
# write csv file for package
write.csv(poc_mvco, "nes-lter-poc-mvco.csv", na = "", row.names = FALSE)
```

Read data table

```{r}

data_table <- read.csv(here('nes-lter-poc-mvco.csv'))

# identify date column for ediutilities package to generate temporal coverage
data_table$date = ymd_hms(data_table$date_time_utc)

```

Read the Excel metadata template and generate text templates used by
EMLassemblyline

```{r}
excel_to_template(here('nes-lter-poc-mvco-info'), 'nes-lter-poc-mvco', rights='CC0')
```
Generate the package and insert the parent project node into the resulting EML

```{r}
# provide package ID
pkg_id <- 'knb-lter-nes.28.1'

make_eml(here(),
         dataset.title='Demonstration of minimal EDI package',
         data.table='nes-lter-poc-mvco.csv',
         data.table.description='Example NES-LTER data',
         data.table.name = 'Subset of NES-LTER nutrient data',
         temporal.coverage = temporal_coverage(data_table$date),
         geographic.description = "NES-LTER Transect",
         geographic.coordinates = geographic_coordinates(data_table$latitude, data_table$longitude),
         maintenance.description = "ongoing",
         user.id = "NES",
         user.domain = "LTER",
         package.id = pkg_id)

project_insert(pkg_id, "parent_project_NESI-II_RAPID.txt")
```
